# Generated by Django 4.1.3 on 2022-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ManyToManyField(to='posts.theme', verbose_name='Thème '),
        ),
    ]
