# Generated by Django 4.1.3 on 2022-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_theme_post_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ManyToManyField(to='posts.theme', verbose_name=''),
        ),
    ]
