# Generated by Django 4.1.3 on 2022-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ManyToManyField(to='posts.theme', verbose_name=''),
        ),
    ]
